import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "../css/pages.css";
import { useModo } from "../context/modoOscuro";
import nuevo from "../assets/nuevo.jpg";
function About() {
    const { modoDark, togleModoDark } = useModo();
    return (_jsx("div", { className: modoDark ? "dark-mode" : "light-mode", children: _jsx("div", { className: "container", children: _jsx("div", { className: "row justify-content-center", children: _jsx("div", { className: "col-md-8", children: _jsx("div", { className: "card p-4 shadow-lg rounded-4", children: _jsxs("div", { className: "card-body", children: [_jsx("div", { style: { width: "200px", height: "200px", margin: "auto" }, children: _jsx("img", { src: nuevo, alt: "nuevo", className: "card-image" }) }), _jsxs("p", { className: "mt-5", children: ["\u00A1Hola! Soy ", _jsx("strong", { children: "FERNANDO RESTREPO" }), ". ", _jsx("strong", { children: "Tecnico en sistemas y desarrollador full-stack." }), _jsx("br", {}), "Apasionado por la creaci\u00F3n de aplicaciones web eficientes y escalables. Me especializo en", _jsx("strong", { children: " React, Javascript, Node.js, Express y MongoDB" }), ", y actualmente sigo perfeccionando mis habilidades en", _jsx("strong", { children: " TypeScript" }), " para generar un codigo m\u00E1s robusto."] }), _jsx("p", { children: "Desde que comenc\u00E9 en el mundo del desarrollo web, me ha fascinado la combinaci\u00F3n de dise\u00F1o y funcionalidad, buscando siempre mejorar la experiencia del usuario con interfaces atractivas y un backend bien optimizado." }), _jsx("h4", { className: "mt-4", children: " Tecnolog\u00EDas que manejo" }), _jsxs("ul", { children: [_jsxs("li", { children: [_jsx("strong", { children: "Frontend:" }), " Javascript, Html, Ccs, React, TypeScript, Bootstrap"] }), _jsxs("li", { children: [_jsx("strong", { children: "Backend:" }), " Node.js,Express, MongoDB"] }), _jsxs("li", { children: [_jsx("strong", { children: "Herramientas:" }), " Git,GitHub"] })] }), _jsx("h4", { className: "mt-4", children: " Qu\u00E9 busco" }), _jsx("p", { children: "Estoy en constante aprendizaje y en busca de nuevas oportunidades para seguir creciendo como desarrollador. Me interesa formar parte de proyectos innovadores donde pueda aportar mis conocimientos y seguir aprendiendo de otros profesionales." }), _jsxs("p", { className: "text-center", children: [_jsx("strong", { children: "\u00BFHablamos?" }), "Escr\u00EDbeme a ", _jsx("strong", { children: "fernandorestrepo@hotmail.es" }), _jsx("br", {}), "o visita mi githube ", _jsx("a", { href: "https://github.com/hfrcmanizales", target: "_blank", rel: "noopener noreferrer", children: "Githube" }), "."] })] }) }) }) }) }) }));
}
export default About;
